### ISSUE TITLE
Error on generating data/flatfile.json

### ISSUE THREAD

**Issue by gregelin** [GovReady/odesurvey#241]
```
Luiss-MacBook-Air:agol_integration audrey$ python agol_integration.py
Parsing data from json file http://www.opendataenterprise.org/map/survey/data/flatfile.json
Traceback (most recent call last):
  File "agol_integration.py", line 112, in <module>
    main(env)
  File "agol_integration.py", line 87, in main
    df = get_parse_content(environment.parse_data_endpoint)
  File "agol_integration.py", line 30, in get_parse_content
    content_response = json.loads(urllib2.urlopen(json_file).read())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by gregelin** [comment]
Looked at PHP log and am seeing:
`[17-Sep-2015 13:35:29] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 71 bytes) in /var/www/html/map/survey/functions.inc.php on line 396`

**Comment by gregelin** [comment]
Increasing allocated memory size for `index.php` script solves problem.
